lightenna_structured_fileview:
    path:      /file/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index }
    requirements:
        rawname:  ".*"

lightenna_structured_imageview:
    path:      /image/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Imageview:index }
    requirements:
        rawname:  ".*"

