lightenna_structured_fileview:
    path:      /file/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index }
    requirements:
        rawname:  ".*"

lightenna_structured_fileview_unspec:
    path:      /file
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index, rawname:'' }

lightenna_structured_fileview_root:
    path:      /
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index, rawname:'' }

lightenna_structured_imageview:
    path:      /image/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Imageview:index }
    requirements:
        rawname:  ".*"

lightenna_structured_imagemeta:
    path:      /imagemeta/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Imageview:meta }
    requirements:
        rawname:  ".*"

lightenna_structured_temppost:
    path:      /post/
    defaults:  { _controller: LightennaStructuredBundle:MetadataPost:create }
    requirements:
        rawname:  ".*"

