lightenna_structured_fileview:
    path:      /file/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index }
    requirements:
        rawname:  ".*"

lightenna_structured_fileview_unspec:
    path:      /file
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index, rawname:'' }

lightenna_structured_fileview_root:
    path:      /
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index, rawname:'' }

images:
    resource: "@LightennaStructuredBundle/Controller/ImageviewController.php"
    type:     annotation

explorers:
    resource: "@LightennaStructuredBundle/Controller/ExplorerviewController.php"
    type:     annotation

