files:
    resource: "@LightennaStructuredBundle/Controller/FileviewController.php"
    type:     annotation

images:
    resource: "@LightennaStructuredBundle/Controller/ImageviewController.php"
    type:     annotation

explorers:
    resource: "@LightennaStructuredBundle/Controller/ExplorerviewController.php"
    type:     annotation

