lightenna_structured_fileview:
    path:      /file/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index }
    requirements:
        rawname:  ".*"

lightenna_structured_fileview_unspec:
    path:      /file
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index, rawname:'' }

lightenna_structured_fileview_root:
    path:      /
    defaults:  { _controller: LightennaStructuredBundle:Fileview:index, rawname:'' }

lightenna_structured_imageview:
    path:      /image/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Imageview:index }
    requirements:
        rawname:  ".*"

lightenna_structured_imageiiif:
    path:      /imageiiif/{identifier}/{region}/{size}/{rotation}/{quality}.{ext}
    defaults:  { _controller: LightennaStructuredBundle:Imageview:iiif }

lightenna_structured_imagemeta:
    path:      /imagemeta/{rawname}
    defaults:  { _controller: LightennaStructuredBundle:Imageview:meta }
    requirements:
        rawname:  ".*"

