parameters:
#    lightenna_structured.example.class: Lightenna\StructuredBundle\Example

services:
#    lightenna_structured.example:
#        class: %lightenna_structured.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
